schema_version = "1.0.0"

id = "addon_id"               # root folder name with underscores
version = "0.1.0"
name = "Addon Name"
tagline = "Addon Description"
maintainer = "Karan"
type = "add-on"
tags = ["Category"]
# website = ""

blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
copyright = ["2022-2024 B3dHub"]

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#     "./wheels/qbpy-1.0.0-py3-none-any.whl",
# ]

# [permissions]
# files = "Add-on saves textures to disk"
